import {PropsWithChildren} from 'react';
import type {Metadata} from 'next';
import {getFontByLanguage} from '@/utils/service/i18n/font';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({children}: PropsWithChildren) {
  const font = await getFontByLanguage();

  return (
    <html lang="en">
    <body className={font.className}>{children}</body>
    </html>
  );
}
