import {PropsWithChildren} from 'react';
import type {Metadata, Viewport} from 'next';
import {getFontByLanguage} from '@/utils/service/i18n/font';
import '@/styles/reset.css';
import '@/styles/global.scss';

// https://docs.google.com/document/d/16UpoOvdENYDO3fHK-YyR70Vet3gyjFbgxT-fwi4R3cY/edit
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: [
      {
        url: `/imgs/favicon.ico`, // 원래 이자리에 사이즈별 아이콘 파일명이 들어가야함.
        sizes: `32x32`,
      },
    ],
    apple: [72, 96, 144].map((size) => ({
      url: `/imgs/favicon.ico`, // 원래 이자리에 사이즈별 아이콘 파일명이 들어가야함.
      sizes: `${size}x${size}`,
    })),
  },
};

export const viewport: Viewport = {
  themeColor: 'white',
};

export default async function RootLayout({children}: PropsWithChildren) {
  const font = await getFontByLanguage();

  return (
    <html lang="en">
    <body className={font.className}>{children}</body>
    </html>
  );
}
